# Generated by Django 4.2.3 on 2023-07-19 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='vote_tally',
            new_name='votes',
        ),
    ]
